site_name: min-react
site_url: https://iliannnn.github.io/min-react/
site_description: Official documentation for min-react
site_author: Iliannnn
repo_url: https://github.com/Iliannnn/min-react
repo_name: Iliannnn/min-react
nav:
  - "Home":
      - "Getting Started": index.md
  - "Components":
      - "Buttons": components/buttons.md
      - "Forms": components/forms.md
      - "Navbars": components/navbars.md
      - "Tables": components/tables.md
      - "Icons": components/icons.md
      - "Grids": components/grids.md
      - "Messages": components/messages.md
  - "Practical Information":
      - "Customizing Components": practical/customizing.md
      - "Contributing": practical/contributing.md

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra_css:
  - assets/stylesheets/extra.css
